language: python
python:
  - "3.7"
  - "3.6"      # current default Python on Travis CI
  - "3.7-dev"  # 3.7 development branch

before_install:
  - pip install -U pip
  - pip install codecov

# command to install dependencies
install:
  - pip install -e ".[test]" .

# command to run tests
script:
  - pytest

after_success:
  - codecov # submit coverage

deploy:
  provider: pypi
  user: "mvernacc"
  password:
    secure: "flxk9S+4m1415MptkJN9EIuW+moyTTZUIPyLq3rzR4kg9w+/qCZqA95+9T6MEekXMNLEKIXVyEUL7vyi8fgq3w1rjWZ2mTpadMjo+wd3jL5YDgbPbiGkyOQXlxBVISPNZUx9WiqVamkLsDlWxpp7jYpsBCD3gsQ0ZGezQAHN+M0y1mBK7CWTatOKigWZhA5bBz0eSCsWNzrWcWgcwKnfCreGulDA5LIdtTDPbwohqLcIBg7SzkP3H6II8Z1bu+9xxc3BWzlk0/Gu70Fu4hMShusykDnVTtKicrtb9+Cxlry16PH/njxkRWS4nn82KsDGjhzgo5wdg4pBs3AJG4w8p9wZ01B0xB6ekGOkG0OV0swDLq9yzuBk1fheW/WjmT+y16B39VcmC52iicIxrT8jkgkoQTUVsgVZ59+YKdC6wZ1H9y34nDKILr5ZGP89Bj0t6rNjxoI9H12/uJc6cVlHA1FV4tbRtrLOaEVhBOZ7hhlg4WWyWcxqBPP4wo+sMVrGSbgTePMVQPf0YvpNAgUyNE4JjWqyNQKAyF22sq0m7pOfE9yCrJrn+v6L7GC+P1DLA+B6YHLAdckcWaQ8QkgwlyJ1EqgQMAOE3kF+TsL4BargSMQr8gjMrk7wtBWtwtlehf5bV0CTrFQOewl7Il57p0KFF9ss2CX1WzmqObRuUq4="
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
