language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch

before_install:
  - pip install -U pip

# command to install dependencies
install:
  - pip install -e ".[test]" .

# command to run tests
script:
  - pytest

after_success:
  - codecov # submit coverage
